### ISSUE TITLE
Gaps in parser tests

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#221]
There is a plan to rewrite the parser to to fix a couple of long standing issues:

1. Having 2 separate parsers, 1 for the code pipeline and another for the readline prompt
2. Nested sub-shells currently do not work

Before that work begins, I want unit tests to check every facet of the existing parser so a rewrite doesn't introduce any breaking changes nor regression bugs.

This ticket is collection of gaps identified in the parser tests

- [ ]  `parser_func_esc_test.go` has commented tests for characters that are not supported by the wrapper function (https://github.com/lmorg/murex/issues/221#issuecomment-641788683)

- [ ] escaped and quote tests one check if function / parameter is only 1 char long

- [ ] escaped and quote tests one check if first character of function / parameter escaped or quoted

- [x]  `parser_pipe_test.go` has conditions that cause a panic (https://github.com/lmorg/murex/issues/221#issuecomment-641790654)

- [ ] `parser_special_cmds_test.go` only checks for `@g` (auto-glob) and `=` (https://github.com/lmorg/murex/issues/221#issuecomment-641795974)

**Comment by lmorg** [comment]
`parser_func_esc_test.go`:

```
// Some of these tests are commented out. This is because those characters
// cannot be used with the wrapper test functions and will instead require
// dedicated test plans written specifically for them

func TestParserFuncEscOrQuote(t *testing.T) {
	tests := []string{
		"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m" /*"n",*/, "o", "p", "q" /*"r",*/ /*"s",*/ /*"t",*/, "u", "v", "w", "x", "y", "z",
		"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
		"1", "2", "3", "4", "5", "6", "7", "8", "9", "0",
		"!" /*`"`,*/, "£", "$", "%", "^", "&", "*", "(", ")", "-", "_", "=", "+", "[", "]", "{", "}", ";", ":" /*"'",*/, "@", "#", "~", "|", ",", "<", ".", ">", "/", "?",
		" ", "\t", "\r", /*"\n",*/
		"世", "界",
		"😀", "😍", "🙏",
	}

	for i := range tests {
		testParserFuncWrapper(t, tests[i])
	}
}

// ...

func TestParserParamEscOrQuote(t *testing.T) {
	tests := []string{
		"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m" /*"n",*/, "o", "p", "q" /*"r",*/ /*"s",*/ /*"t",*/, "u", "v", "w", "x", "y", "z",
		"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
		"1", "2", "3", "4", "5", "6", "7", "8", "9", "0",
		"!" /*`"`,*/, "£" /*"$",*/, "%", "^", "&", "*", "(", ")", "-", "_", "=", "+", "[", "]", "{", "}", ";", ":" /*"'",*/ /*"@",*/, "#" /*"~",*/, "|", ",", "<", ".", ">", "/", "?",
		" ", "\t", "\r", /*"\n",*/
		"世", "界",
		"😀", "😍", "🙏",
	}

	for i := range tests {
		testParserFuncWrapper(t, tests[i])
	}
}
```

**Comment by lmorg** [comment]
`parser_pipe_test.go` has a commented out test because test causes panic. Panic needs to be fixed:

```go
		/*{
			Block: `=>foo`,
			Expected: []parserTestSimpleExpected{
				{
					Name:       "foo",
					Parameters: []string{},
					Method:     TEST_METHOD,
				},
			},
		},
		{
			Block: `=> foo`,
			Expected: []parserTestSimpleExpected{
				{
					Name:       "foo",
					Parameters: []string{},
					Method:     TEST_METHOD,
				},
			},
		},
		{
			Block: `  =>  foo`,
			Expected: []parserTestSimpleExpected{
				{
					Name:       "foo",
					Parameters: []string{},
					Method:     TEST_METHOD,
				},
			},
		},*/
```

**Comment by lmorg** [comment]
`parser_special_cmds_test.go` only checks for `@g` (auto-glob) and `=`.

Other checks might include:

- [ ] `$` (variable)

- [ ] `(` (string)

- [ ] `#` (comment)

- [ ] `^` (REPL variable)

- [ ] `~` (POSIX home)

- [ ] `{` (code block)

- [ ] `<` (redirection)

- [ ] `[` (index)

- [ ] `[[` (element)

Plus perhaps any closing brackets too:

- [ ] `}`

- [ ] `]`

- [ ] `)`

**Comment by lmorg** [comment]
74ad319 and 18b1191  contain additional parser and compiler tests for [parser_pipe_test.go](https://github.com/lmorg/murex/issues/221#issuecomment-641790654)

**Comment by lmorg** [comment]
Parser has been completely rewritten.
